import { useEffect, useState } from 'react';
import type { OwnedWorktreeV2, WorktreePreviewV2 } from '@agent-dock/shared';

export function WorktreePanel({ cwd }: { cwd: string }) {
  const [name, setName] = useState(''); const [preview, setPreview] = useState<WorktreePreviewV2>(); const [confirmed, setConfirmed] = useState(false); const [items, setItems] = useState<OwnedWorktreeV2[]>([]); const [error, setError] = useState<string>();
  const refresh = () => window.agentDock.listWorktrees().then(setItems).catch((failure: unknown) => setError(failure instanceof Error ? failure.message : 'Worktree list failed'));
  useEffect(() => { void refresh(); }, []);
  async function inspect() { try { setPreview(await window.agentDock.previewWorktree({ cwd: cwd.trim(), name: name.trim() })); setConfirmed(false); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Worktree preview failed'); } }
  async function create() { if (!preview || !confirmed) return; try { await window.agentDock.createWorktree({ cwd: cwd.trim(), name: preview.name, confirmIncludeCopy: true }); setPreview(undefined); setName(''); await refresh(); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Worktree creation failed'); } }
  return <div>{error && <div className="banner banner--error">{error}</div>}<div className="row"><input aria-label="Worktree name" value={name} onChange={(event) => setName(event.target.value)} placeholder="feature-name" /><button type="button" disabled={!cwd.trim() || !name.trim()} onClick={() => void inspect()}>Preview</button></div>{preview && <div className="worktree-preview"><p>Copy {preview.includeFiles.length} included file(s); {preview.ignoredFiles.length} ignored file(s) detected.</p>{preview.secretRisk && <p className="mcp-server__failure">Possible secret-bearing filenames detected. Review before copying.</p>}<label><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /> I reviewed the include and ignored-file preview.</label><button type="button" disabled={!confirmed} onClick={() => void create()}>Create isolated worktree</button></div>}<div className="component-list">{items.map((item) => <div className="component-item" key={item.id}><div className="row row--spread"><strong>{item.name}</strong><span>{item.status}</span></div>{item.status === 'ready' && <button type="button" onClick={() => void window.agentDock.cleanupWorktree(item.id).then(refresh).catch((failure: unknown) => setError(failure instanceof Error ? failure.message : 'Cleanup blocked'))}>Clean up</button>}</div>)}</div></div>;
}
